pipeline {
   agent any
   stages{
    stage('CodeScan'){
        steps{
            sh 'trivy fs . -o result.html'
            sh 'cat result.html'
        }
    }
    stage{
        steps{
          sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 029571729512.dkr.ecr.us-east-1.amazonaws.com'  
        }
    }
    stage('dockerImageBuild'){
        steps{
            sh 'docker build -t jenkins-ci''
        }
}
    stage('pushImage'){
        steps{
            sh 'docker ps'
        }
    }
   } 
}